blue:
  max:
  - 255
  - 157
  - 114
  min:
  - 51
  - 0
  - 0
green:
  max:
  - 179
  - 101
  - 215
  min:
  - 33
  - 20
  - 0
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 150
  - 130
